FROM pytorch/pytorch

WORKDIR /python-docker

COPY requirements-docker.txt requirements.txt
RUN apt-get update
RUN apt-get install -y ffmpeg
# RUN apt-get install git -y
RUN pip3 install -r requirements.txt
# RUN pip3 install "git+https://github.com/openai/whisper.git"
RUN pip install openai-whisper
