FROM python:3.10-slim

WORKDIR /python-docker

COPY requirements-docker.txt requirements.txt
RUN apt-get update && apt-get install git -y
RUN apt-get install -y ffmpeg
RUN pip3 install -r requirements.txt
RUN pip3 install "git+https://github.com/openai/whisper.git" 
