apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: whisper-asr
  name: whisper-asr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: whisper-asr
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: whisper-asr
    spec:
      containers:
        - name: whisper-asr
          image: onsei/whisper-asr:0.3.1.0005
          ports:
            - containerPort: 8765
          resources: {}
      imagePullSecrets:
        - name: dockerhubsecret
      restartPolicy: Always
status: {}
